spring:
    application:
        name: apigateway
zuul:
    prefix: /aplicativos
feign: 
    routes:
            autenticacion:
                path: /autenticacion/**
            periodo-academico-service:
                path: /periodo-academico-service/**
            asistencia-service:
                path: /asistencia-service/**
    hystrix:
        enabled: true
# Increase the Hystrix timeout to 60s (globally)
hystrix:
    command:
        default: 
            execution: 
                isolation:
                    thread: 
                        timeoutInMilliseconds: 60000
                timeout:
                    enabled: false
    shareSecurityContext: true
#Ribbon Configuration
ribbon:
  eureka:
    enable: true
  ConnectTimeout: 10000
  ReadTimeout: 10000
