spring:
    application:
        name: apigateway
zuul:
    prefix: /aplicativos
    sensitive-headers:
    add-proxy-headers: true

# Increase the Hystrix timeout to 60s (globally)
hystrix:
    command:
        default: 
            execution: 
                isolation:
                    thread: 
                        timeoutInMilliseconds: 60000
                timeout:
                    enabled: false
    shareSecurityContext: true

feign: 
    hystrix:
        enabled: true

#Ribbon Configuration
ribbon:
  eureka:
    enable: true
