spring:
    application:
        name: apigateway
zuul:
    prefix: /aplicativos
feign: 
    hystrix:
        enabled: true
#Ribbon Configuration
ribbon:
  eureka:
    enable: true
  ConnectTimeout: 10000
  ReadTimeout: 10000
